### ISSUE TITLE
disk fixity can crash when package deleted after checklist generated

### ISSUE THREAD

**Issue by grf** [daitss/silo-pool#5]
the disk was being fixity checked when the file was deleted on a refresh; bad timing, it disappeared out from under the check.  It should be easy to fix the bug (just needs to catch the error and double check if it was deleted and then either:

1) log an error and record it as missing and move on, or
2) just move on if it really was properly deleted

```
/opt/web-services/sites/silos/current/lib/store/silo.rb:307:in `md5': Can't determine md5 for 'E20060816_AAACGI' (located at '/daitssfs/007/68f/ab940396a03793eb754264bc88a34'): No such file or directory - /daitssfs/007/68f/ab940396a03793eb754264bc88a34/md5 (Store::SiloError)
       from /opt/web-services/sites/silos/current/lib/store/silo.rb:403:in `read_lock'
       from /opt/web-services/sites/silos/current/lib/store/silo.rb:401:in `open'
       from /opt/web-services/sites/silos/current/lib/store/silo.rb:401:in `read_lock'
       from /opt/web-services/sites/silos/current/lib/store/silo.rb:303:in `md5'
       from /opt/web-services/sites/silos/current/tools/disk-fixity:195
       from /opt/web-services/sites/silos/current/lib/store/silodb.rb:141:in `each_package_record'
       from /opt/web-services/sites/silos/shared/bundle/ruby/1.8/gems/dm-core-1.2.0/lib/dm-core/collection.rb:507:in `each'
       from /opt/web-services/sites/silos/shared/bundle/ruby/1.8/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in `each'
       from /opt/web-services/sites/silos/shared/bundle/ruby/1.8/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in `each'
       from /opt/web-services/sites/silos/shared/bundle/ruby/1.8/gems/dm-core-1.2.0/lib/dm-core/collection.rb:504:in `each'
       from /opt/web-services/sites/silos/current/lib/store/silodb.rb:141:in `each_package_record'
       from /opt/web-services/sites/silos/current/tools/disk-fixity:158
       from /opt/web-services/sites/silos/current/tools/disk-fixity:152:in `each'
       from /opt/web-services/sites/silos/current/tools/disk-fixity:152
```

[prb.fcla.edu #15324] 

[core] disk-fixity: repeated crashes (#603)

**Comment by lydiam** [comment]
It seems unlikely that the Nov. 29 crash and the Dec. 9 crash stemmed 
from the same problem, since AIP

E20060816_AAACGI was successfully refreshed on Nov. 29.  What caused the Dec. 9 crash and why was no information logged? (see #603).

I'll proceed to delete the current disk-fixity.pid file.

On 12/13/2011 11:38 AM, Randy Fischer wrote:

> the disk was being fixity checked when the file was deleted on a refresh; bad timing, it disappeared out from under the check.  It should be easy to fix the bug (just needs to catch the error and double check if it was deleted and then either:
> 
> 1) log an error and record it as missing and move on, or
> 2) just move on if it really was properly deleted
> 
> ```
>  /opt/web-services/sites/silos/current/lib/store/silo.rb:307:in `md5': Can't determine md5 for 'E20060816_AAACGI' (located at '/daitssfs/007/68f/ab940396a03793eb754264bc88a34'): No such file or directory - /daitssfs/007/68f/ab940396a03793eb754264bc88a34/md5 (Store::SiloError)
>         from /opt/web-services/sites/silos/current/lib/store/silo.rb:403:in `read_lock'
>         from /opt/web-services/sites/silos/current/lib/store/silo.rb:401:in `open'
>         from /opt/web-services/sites/silos/current/lib/store/silo.rb:401:in `read_lock'
>         from /opt/web-services/sites/silos/current/lib/store/silo.rb:303:in `md5'
>         from /opt/web-services/sites/silos/current/tools/disk-fixity:195
>         from /opt/web-services/sites/silos/current/lib/store/silodb.rb:141:in `each_package_record'
>         from /opt/web-services/sites/silos/shared/bundle/ruby/1.8/gems/dm-core-1.2.0/lib/dm-core/collection.rb:507:in `each'
>         from /opt/web-services/sites/silos/shared/bundle/ruby/1.8/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in `each'
>         from /opt/web-services/sites/silos/shared/bundle/ruby/1.8/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in `each'
>         from /opt/web-services/sites/silos/shared/bundle/ruby/1.8/gems/dm-core-1.2.0/lib/dm-core/collection.rb:504:in `each'
>         from /opt/web-services/sites/silos/current/lib/store/silodb.rb:141:in `each_package_record'
>         from /opt/web-services/sites/silos/current/tools/disk-fixity:158
>         from /opt/web-services/sites/silos/current/tools/disk-fixity:152:in `each'
>         from /opt/web-services/sites/silos/current/tools/disk-fixity:152
> ```
> 
> [prb.fcla.edu #15324]
> 
> [core] disk-fixity: repeated crashes (#603)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/daitss/silo-pool/issues/5

## 

Lydia Motyka
Manager, Florida Digital Archive
(352)392-9020 x328
